lisafast/react-answers

api/chatgpt.js, api/claude-batch.js, api/claude.js, api/gpt-batch.js, config/ai-models.js
Add a config file with all the model details so they're not hardcoded in the api endpoints.
=> make config file and update gpt4o

api/chatgpt.js, api/claude.js, config/ai-models.js, src/components/chat/ChatAppContainer.js, src/services/CitationService.js, src/services/ClaudeService.js, src/services/citationSystemPromptBuilder.js, src/services/systemPrompt/base.js, src/services/systemPrompt/context-cra/cra-scenarios.js, src/services/systemPrompt/context-cra/cra-sitemap.js, src/services/systemPrompt/context-esdc/esdc-sitemap.js, src/services/systemPrompt/context-isc/isc-sitemap.js, src/services/systemPrompt/scenarios-all.js
Need to just add some of the files from this useless attempt to use Haiku to find citation url because it changed the claude endpoint and claude service so can call haiku if needed (just need to change 'citation' to 'context' and change system prompt. 
Well ok a fair amount to change but need to keep this branch to make that new ContextService from.
=> AI citation service attempt and failure 

api/claude-haiku.js, server/server.js, src/components/chat/ChatAppContainer.js, src/components/chat/DepartmentSelectorTesting.js, src/hooks/usePageParam.js, src/services/ClaudeService.js, src/services/ContextService.js, src/services/contextSystemPrompt.js, src/services/systemPrompt/departments_EN.js, src/services/systemPrompt/departments_Fr.js
Call to smaller faster cheaper Haiku model to derive department and topic for the user question. Passes them to main call. Then can remove menu-structure loading from main answer call.
=> Context service LLM as a judge

src/components/chat/ChatAppContainer.js, src/services/ContextService.js, src/services/contextSystemPrompt.js
add department url to message to main AI call to help it with citation
=> fine tuning - relay department URL with name

README.md, src/components/chat/ChatAppContainer.js
=> fix display ui issue for new service 

README.md, src/components/chat/ChatAppContainer.js, src/services/contextSystemPrompt.js, src/services/systemPrompt/menuStructure_EN.js, src/services/systemPrompt/menuStructure_FR.js
add more to menu structure
be firmer about using most requested pages if good match
=> fix citations issue in chatAppContainer 

src/components/chat/ChatAppContainer.js, src/locales/en.json, src/locales/fr.json, src/services/systemPrompt/base.js
and set default back to Claude
=> Add user display message for haiku call for context 

src/components/admin/ChatLogsDashboard.js
Could still click button and see logs
=> Admin code wasn't working

models/chat/interaction.js, src/components/admin/ChatLogsDashboard.js, src/components/chat/ExpertRatingComponent.js, src/locales/en.json, src/locales/fr.json, src/services/systemPrompt/context-ircc/ircc-scenarios.js
Each element of the AI response can be coded/evaluated separately.
=> Change expert rating

src/components/chat/ChatInterface.js, src/locales/en.json, src/locales/fr.json, src/services/RedactionService.js, src/services/redactions/manipulation_en.json, src/services/systemPrompt/context-ircc/ircc-scenarios.js, src/services/systemPrompt/context-ircc/ircc-updates.js
ChatInterace is not displaying the PrivacyMessage or the BlockedMessage in the question block. Timing is wrong - it is looking for XXX and ### before they are put in by RedactionService.
Also fixed error in IRCC Updates file. 
Added a few words to Manipulation
=> attempted to fix messages & IRCC prompt change

src/components/chat/ChatInterface.js, src/styles/App.css
redacted message wasn't showing up - mostly a css issue but also simplified logic
=> css + chatinterface fix

agents/AgentService.js, api/chatgpt.js, api/claude-batch.js, api/context-agent.js, package-lock.json, package.json, server/server.js, src/components/admin/ChatLogsDashboard.js, src/components/admin/Evaluator.js, src/pages/AdminPage.js, src/services/systemPrompt/agenticBase.js
=> Failover context service fix

config/ai-models.js, src/components/chat/ChatAppContainer.js, src/services/ChatGPTService.js, src/services/ClaudeService.js, src/services/CohereService.js, src/services/systemPrompt.js
Context is now added to the system prompt instead of in the user message. It is also added higher up in the prompt to ensure the departmental scenarios/updates take precedence.
=> System prompt context fix

agents/tools/checkURL.js, api/chatgpt.js, api/claude.js, src/components/chat/ChatInterface.js, src/services/ClaudeService.js, src/services/contextSystemPrompt.js
Merging fix from Ryan, changing to custom change method for control
=> Firefox input fix

api/chatgpt.js, api/claude.js
It looks like sometimes claude will return a blank message. I've added a check for this to use the failover if this is the case.
=> Timeout fix

agents/AgentService.js, agents/tools/contextSearch.js, api/context-agent.js, src/services/contextSystemPrompt.js
Search is now executed before call to LLM.
=> Break out search

src/services/LoggingService.js, src/services/database.js
Fixees for log-interaction and database connect
=> Logging fixes

api/db-chat-logs.js, src/components/admin/ChatLogsDashboard.js, src/components/chat/ChatAppContainer.js
System prompt now has new fields for english-answer, page-language, question-language etc. Adding them into the csv file.
=> add new fields

src/components/admin/ChatLogsDashboard.js, src/services/systemPrompt/context-cra/cra-scenarios.js, src/services/systemPrompt/context-ircc/ircc-scenarios.js, src/services/systemPrompt/context-pspc/pspc-scenarios.js, src/services/systemPrompt/context-pspc/pspc-updates.js
more error catching in chatlogs
also fix examples in scenarios files to remove 'citation-url-en' because claude used that instead of plain 'citation-url' and caused the url to not be displayed or logged.
=> Adminpage chatlogs

src/components/admin/ChatLogsDashboard.js, src/components/chat/ChatAppContainer.js
had the wrong operator of || instead of ?? so scores of zero were being stored as empty/null. Now stored in db as numbers.
=> fix how scores are saved into db

src/services/contextSystemPrompt.js, src/services/systemPrompt.js, src/services/systemPrompt/context-cra/cra-scenarios.js, src/services/systemPrompt/context-cra/cra-updates.js
remove reference to search tool, add more structure to constrain AI from making up topics and topic urls.
=> extensive rewrite

src/services/systemPrompt/agenticBase.js
previous attempt didn't work, still added up tfsa contribtuion room and both AI's got it wrong.
=> try again on math prohibition

api/anthropic-batch.js, api/openai-batch-process-results.js, api/openai-batch.js
Context data was not being passed to final spreadsheet.
=> Fix for context not being passed, and for no answer tokens

src/services/RedactionService.js
to catch many more long alphanumeric number sequences with and without separators of . -  and space.
=> expanded number pattern

src/services/RedactionService.js
hadn't caught error when testing. Bad me
=> redaction pattern was broken

src/services/contextSystemPrompt.js, src/services/systemPrompt/citationInstructions.js
two prompts had referring-url misspelled
=> consistent use of referring-url tag

src/components/chat/ChatAppContainer.js, src/services/ChatPipelineService.js
Remove bug in status message updates
=> Feature true message

api/anthropic-batch-context.js, api/anthropic-context.js, api/openai-batch-context.js, api/openai-context.js, api/search-context.js, services/ContextAgentService.js, src/services/ChatPipelineService.js, src/services/ContextService.js, src/services/__tests__/ContextService.test.js, src/utils/backoff.js
- Fixed referring URL, by ensuring prepareMessage is used by both batch and sendMessage
- Refactored some of the batch code that was repeated and unused.
-
=> Fixed a few bugs with batches

src/services/systemPrompt/departments_EN.js, src/services/systemPrompt/departments_FR.js
=> Replace all http: with https: 

src/services/systemPrompt/agenticBase.js, src/services/systemPrompt/scenarios-all.js
These were all previously in menu-structure - along with a lot of other page urls.
=> add life event page updates

README.md
=> removed topic from context service

src/components/chat/ExpertRatingComponent.js
assume unscored items are 'good' - only consider sentences that are present for the calculation. Address issue #200
=> revise calculation of score

config/ai-models.js, src/services/RedactionService.js
did not update Haiku
deleted caching call because it's no longer in beta - need to add back in
=> update to claude 3.7.

src/services/systemPrompt/context-cra/cra-scenarios.js
both ai services say you can see it on NOA but that is no longer true
=> add TFSA issue to CRA

src/services/RedactionService.js, src/services/systemPrompt/scenarios-all.js
=> Simplify prompts - SIN number

src/components/chat/ExpertRatingComponent.js
Reverts lisafast/react-answers#250
=> Revert "Css updates v2"

src/services/systemPrompt.js
Explored combining department files into a single file but not possible since there are 200+ and the files don't have a key to match them.
=> added mapping of French department abbreviations

src/services/systemPrompt/context-esdc/esdc-scenarios.js, src/services/systemPrompt/scenarios-all.js
=> phone number advice

src/services/systemPrompt/agenticBase.js
AI was being too parsimonious about when to use the download tool - expanded instructions to try and get it to use it more often.
=> expand download tool instructions

README.md, config/ai-models.js, src/locales/en.json, src/locales/fr.json
=> update all to GPT 4.1

package-lock.json, src/components/chat/ChatAppContainer.js, src/components/chat/ChatInterface.js, src/locales/en.json, src/locales/fr.json, src/pages/HomePage.js
@lisafast @ryanhyma 
Fixed "cah" being called, added aria label to textarea. There's a broken object when submitting a Q but I want you to be aware of what I'm working on
=> Accessibility

src/components/chat/ChatAppContainer.js, src/locales/en.json, src/locales/fr.json
small piece of code to have redaction error messages played to screenreader users.
=> handle-redaction

src/services/systemPrompt/context-ircc/ircc-scenarios.js
clarifying question in ircc scenario
=> Ircc pepin edits

agents/tools/downloadWebPage.js
Ryan - Kate noticed the tool didn't seem to be reading the contents of the table on this page - it's really been troubling her : https://www.sac-isc.gc.ca/eng/1595274954300/1595274980122
I asked Cursor if it was likely the tool wasn't reading the tables correctly and it said no it wasn't. 
It suggested code, and then I threw these important table pages at it and asked it to make the code read them properly too: 
Border wait times: https://www.cbsa-asfc.gc.ca/bwt-taf/menu-eng.html
Contact all: https://www.canada.ca/en/contact.html
SIgn in: https://www.canada.ca/en/government/sign-in-online-account.html
Careful - this code was cursor generated.
=> tool wasn't reading table contents

src/locales/en.json, src/locales/fr.json
=> change email address in About expand-collapse

src/services/systemPrompt/context-cra/cra-scenarios.js, src/services/systemPrompt/scenarios-all.js
=> fix from sign in testing and updates

src/services/systemPrompt/agenticBase.js
PROMPT only 
clarify generate-context instructions
instruct to not use multi-tool
=> fix-tool-instructions

src/services/systemPrompt/citationInstructions.js
PROMPT only 
seems to fail to generate a citation if it will be the same as previous citation. Gave specific instruction.
=> fix-citation-issue

.github/workflows/deploy-app-runner.yml
=> chore: add spaces to test infra
